name: Build Buylist
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests xlrd==2.0.1 pillow
      - name: Generate pages
        env:
          EXCEL_PATH: ${{ secrets.EXCEL_PATH }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          OUT_DIR: docs
        run: python generate_buylist.py
      - name: Commit docs
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          if git diff --cached --quiet; then
            echo 'no changes'
          else
            git commit -m 'build: buylist pages'
            git push
          fi
