name: Fetch POS & Sync to Sheets

on:
  schedule:
    - cron: "*/15 * * * *"   # 15分おき（UTC）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Run fetcher
        env:
          POS_EMAIL: ${{ secrets.POS_EMAIL }}
          POS_PASSWORD: ${{ secrets.POS_PASSWORD }}
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
          GAS_SHARED_SECRET: ${{ secrets.GAS_SHARED_SECRET }}
          GENRE_ID: "137"
          POS_BASE: "https://pos.mycalinks.com"
        run: npm run fetch
