name: Build & Publish buylist

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: buylist-publish
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache は使わない → 例の「requirements が無い」警告を消す

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pillow requests

      - name: Sanity check (必要ファイルがあるか)
        run: |
          set -e
          if [ ! -f gen_buylist.py ]; then
            echo "::error::gen_buylist.py がリポジトリのルートにありません"; exit 1
          fi
          INPUT=""
          for p in data/buylist.xlsx buylist.xlsx data/buylist.csv buylist.csv; do
            if [ -f "$p" ]; then INPUT="$p"; break; fi
          done
          if [ -z "$INPUT" ]; then
            echo "::error::データファイルが見つかりません。buylist.xlsx（または data/buylist.xlsx / buylist.csv）を配置してください"; exit 1
          fi
          echo "INPUT=$INPUT" >> $GITHUB_ENV

      - name: Build static pages
        env:
          OUT_DIR: docs
          PER_PAGE: "80"
          BUILD_THUMBS: "0"
        run: |
          python gen_buylist.py "$INPUT"

      - name: Commit & push docs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if git diff --cached --quiet; then
            echo "No changes in docs/"
          else
            git commit -m "update buylist (auto)"
            git push
          fi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps (Node)
        run: npm ci

      - name: Run fetcher
        run: npm run fetch
        env:
          POS_EMAIL: ${{ secrets.POS_EMAIL }}
          POS_PASSWORD: ${{ secrets.POS_PASSWORD }}
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
          GAS_SHARED_SECRET: ${{ secrets.GAS_SHARED_SECRET }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps (Python)
        run: pip install -r requirements.txt

      - name: Build static pages
        run: python gen_buylist.py
