name: Build & Publish buylist (Self-hosted Runner)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: buylist-publish
  cancel-in-progress: true

jobs:
  build:
    # ← 自前ランナーに切替（config時に --labels local を付けた前提）
    runs-on: [self-hosted, local]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pillow requests

      # ===== POS から取得（URL/Cookie をサニタイズ、403対策の追加ヘッダ、デバッグ保存） =====
      - name: Fetch from POS (pwsh, robust + sanitize + debug)
        id: fetch
        env:
          POS_FILE_URL:       ${{ secrets.POS_FILE_URL }}        # 最終URLを1行で
          POS_COOKIE:         ${{ secrets.POS_COOKIE }}          # DevTools→NetworkのCookie全体（1行）
          POS_AUTH_HEADER:    ${{ secrets.POS_AUTH_HEADER }}     # 任意: 例 "Authorization: Bearer xxxxx"
          POS_X_CSRF_HEADER:  ${{ secrets.POS_X_CSRF_HEADER }}   # 任意: 例 "x-csrf-token: yyy"
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path data | Out-Null

          # --- Sanitize URL/Cookie（改行/外側のクォート/Windowsの ^ を除去） ---
          $url = ($env:POS_FILE_URL   ?? "") -replace "`r|`n",""
          $url = $url.Trim('"').Trim("'").Trim()
          $url = $url -replace '\^&','&' -replace '\^',''
          if ($url -notmatch '^https?://') { throw "POS_FILE_URL が不正（http/httpsで始まっていない）" }

          $cookie = ($env:POS_COOKIE ?? "") -replace "`r|`n",""

          # --- 秘密をマスク ---
          Write-Output "::add-mask::$url"
          if ($cookie)            { Write-Output "::add-mask::$cookie" }
          if ($env:POS_AUTH_HEADER)   { Write-Output "::add-mask::$($env:POS_AUTH_HEADER)" }
          if ($env:POS_X_CSRF_HEADER) { Write-Output "::add-mask::$($env:POS_X_CSRF_HEADER)" }

          # --- ブラウザっぽいヘッダ ---
          $headers = @{
            "User-Agent"         = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
            "Accept"             = "*/*"
            "Accept-Language"    = "ja,en-US;q=0.9,en;q=0.8"
            "Content-Type"       = "application/json"
            "Referer"            = "https://pos.mycalinks.com/auth/item?genreId=137"
            "Origin"             = "https://pos.mycalinks.com"
            "Sec-Fetch-Dest"     = "empty"
            "Sec-Fetch-Mode"     = "cors"
            "Sec-Fetch-Site"     = "same-origin"
            "sec-ch-ua"          = 'Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"'
            "sec-ch-ua-mobile"   = "?0"
            "sec-ch-ua-platform" = "Windows"
            "X-Requested-With"   = "XMLHttpRequest"
          }
          if ($cookie) {
            $headers["Cookie"] = $cookie
          }
          if ($env:POS_AUTH_HEADER) {
            $k,$v = $env:POS_AUTH_HEADER.Split(":",2); if ($v) { $headers[$k.Trim()] = $v.Trim() }
          }
          if ($env:POS_X_CSRF_HEADER) {
            $k,$v = $env:POS_X_CSRF_HEADER.Split(":",2); if ($v) { $headers[$k.Trim()] = $v.Trim() }
          }

          # --- 取得：成功/失敗でも headers/body を保存 ---
          $code = 0
          try {
            $resp = Invoke-WebRequest -Uri $url -Headers $headers -Method GET -MaximumRedirection 5 -ErrorAction Stop -OutFile data/raw.bin
            $code = $resp.StatusCode
            $resp.Headers.GetEnumerator() | ForEach-Object { "$($_.Key): $($_.Value)" } | Set-Content -Encoding ASCII data/headers.txt
          } catch {
            if ($_.Exception.Response) {
              $code = $_.Exception.Response.StatusCode.value__
              $_.Exception.Response.Headers.GetEnumerator() | ForEach-Object { "$($_.Key): $($_.Value)" } | Set-Content -Encoding ASCII data/headers.txt
              Copy-Item -Force data/raw.bin data/error_body.bin -ErrorAction SilentlyContinue
            } else { throw }
          }

          "HTTP $code" | Write-Host
          Get-Content data/headers.txt -TotalCount 50 -EA SilentlyContinue | Write-Host

          if ($code -ne 200) {
            throw "HTTP $code（Cookie期限切れ/WAFの可能性）。headers.txt / error_body.bin を確認。"
          }

          # --- Content-Type で保存名を振り分け ---
          $ctype = (Get-Content data/headers.txt | Select-String -Pattern '^content-type:' -SimpleMatch -CaseSensitive:$false | Select-Object -Last 1).ToString()
          $ctype = ($ctype -replace '^[^:]+:\s*','').ToLower().Split(';')[0]
          if ($ctype -match 'application/json') {
            Move-Item -Force data/raw.bin data/items.json
          } elseif ($ctype -match 'application/(vnd\.openxmlformats\-officedocument\.spreadsheetml\.sheet|octet-stream)') {
            Move-Item -Force data/raw.bin data/buylist.xlsx
          } elseif ($ctype -match 'text/csv|application/csv') {
            Move-Item -Force data/raw.bin data/buylist.csv
          } else {
            # 先頭1byteでJSONっぽさを推定
            $first = [System.Text.Encoding]::ASCII.GetString([System.IO.File]::ReadAllBytes("data/raw.bin"),0,1)
            if ($first -eq '{') { Move-Item -Force data/raw.bin data/items.json } else { Move-Item -Force data/raw.bin data/buylist.xlsx }
          }

          Get-ChildItem data

      # ===== JSON だった場合は CSV に変換（pwsh で一時スクリプトを作る方式） =====
      - name: Convert JSON to CSV (generic)
        if: ${{ hashFiles('data/items.json') != '' }}
        shell: pwsh
        run: |
          $code = @'
          import json, pandas as pd
          from pandas import json_normalize
          import pathlib
          p = pathlib.Path("data/items.json")
          data = json.load(p.open(encoding="utf-8"))
          if isinstance(data, dict):
              for key in ("items","data","products","result","value"):
                  if key in data and isinstance(data[key], list):
                      data = data[key]; break
          if not isinstance(data, list):
              data = [data]
          df = json_normalize(data, sep=".")
          df.to_csv("data/buylist.csv", index=False, encoding="utf-8")
          print(f"Wrote data/buylist.csv rows={len(df)} cols={len(df.columns)}")
          '@
          $code | Set-Content -Encoding UTF8 .\convert_json_to_csv.py
          python .\convert_json_to_csv.py
          Get-ChildItem data

      # ===== 静的ページ生成（あなたの gen_buylist.py を使用） =====
      - name: Build static pages
        shell: pwsh
        env:
          OUT_DIR: docs
          PER_PAGE: "80"
          BUILD_THUMBS: "0"
        run: |
          $input = @("data\buylist.xlsx","data\buylist.csv","buylist.xlsx","buylist.csv") | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $input) { throw "入力データがありません（POS取得失敗 & リポジトリにも無い）" }
          python gen_buylist.py $input

      # ===== 公開用 docs/ をコミット =====
      - name: Commit & push docs
        shell: pwsh
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if (git diff --cached --quiet) {
            Write-Host "No changes in docs/"
          } else {
            git commit -m "update buylist (auto)"
            git push
          }

      # ===== 失敗時でもヘッダ/本文を拾えるように =====
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pos-debug
          path: |
            data/headers.txt
            data/error_body.bin
