name: Publish Buylist

on:
  workflow_dispatch:   # 手動実行用
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Check secrets presence
        run: |
          echo POS_API_URL set? ${{ secrets.POS_API_URL != '' || vars.POS_API_URL != '' }}
          echo POS_COOKIE set? ${{ secrets.POS_COOKIE != '' || vars.POS_COOKIE != '' }}
          echo GAS_WEBHOOK_URL set? ${{ secrets.GAS_WEBHOOK_URL != '' || vars.GAS_WEBHOOK_URL != '' }}
          echo GAS_SHARED_SECRET set? ${{ secrets.GAS_SHARED_SECRET != '' || vars.GAS_SHARED_SECRET != '' }}

      - name: Run fetcher
        run: npm run fetch
        env:
          POS_API_URL: ${{ secrets.POS_API_URL || vars.POS_API_URL }}
          POS_COOKIE: ${{ secrets.POS_COOKIE || vars.POS_COOKIE }}
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL || vars.GAS_WEBHOOK_URL }}
          GAS_SHARED_SECRET: ${{ secrets.GAS_SHARED_SECRET || vars.GAS_SHARED_SECRET }}

      - name: Build site
        run: python gen_buylist.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
