name: "Build & Publish buylist (self-hosted, paginated)"

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  # schedule:
  #   - cron: "*/30 * * * *"  # 30分毎（UTC）。使うときはコメント解除

permissions:
  contents: write

concurrency:
  group: buylist-publish
  cancel-in-progress: true

jobs:
  build:
    # 自前ランナーのラベルに合わせて調整。例では Windows & local ラベルを想定
    runs-on: [ self-hosted, Windows, local ]

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pillow requests

      # ========= POS からページング取得（/auth?currentPage=… と /api?take&skip=… の両対応）=========
      - name: Fetch from POS (paginate)
        env:
          POS_FILE_URL:       ${{ secrets.POS_FILE_URL }}
          POS_COOKIE:         ${{ secrets.POS_COOKIE }}
          POS_AUTH_HEADER:    ${{ secrets.POS_AUTH_HEADER }}
          POS_X_CSRF_HEADER:  ${{ secrets.POS_X_CSRF_HEADER }}
          POS_MAX_PAGES:      50
          POS_PAGE_SIZE:      100
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path data | Out-Null

          function Sanitize([string]$s){
            if ($null -eq $s) { return '' }
            ($s -replace "`r|`n",' ') -replace '\^&','&' -replace '\^','' | ForEach-Object { $_.Trim('"').Trim("'").Trim() }
          }
          function FirstNonEmpty([string[]]$vals){
            foreach($v in $vals){ if ($null -ne $v -and $v.Trim() -ne ''){ return $v } }
            return $null
          }

          $Url  = Sanitize $env:POS_FILE_URL
          if ($Url -notmatch '^https?://') { throw 'POS_FILE_URL must start with http/https' }
          $Cook = Sanitize $env:POS_COOKIE
          $Auth = Sanitize $env:POS_AUTH_HEADER
          $Csrf = Sanitize $env:POS_X_CSRF_HEADER

          Write-Output ("::add-mask::" + $Url)
          if ($Cook) { Write-Output ("::add-mask::" + $Cook) }
          if ($Auth) { Write-Output ("::add-mask::" + $Auth) }
          if ($Csrf) { Write-Output ("::add-mask::" + $Csrf) }

          Add-Type -AssemblyName System.Web
          function Set-Q([string]$u,[string]$k,[string]$v){
            $uri=[Uri]$u
            $qs=[System.Web.HttpUtility]::ParseQueryString($uri.Query)
            $qs.Set($k,$v)
            $b=[UriBuilder]::new($uri)
            $b.Query=$qs.ToString()
            $b.Uri.AbsoluteUri
          }

          $qs=[System.Web.HttpUtility]::ParseQueryString(([Uri]$Url).Query)
          $hasPage = ($qs.AllKeys -contains 'currentPage') -or ($Url -like '*/auth/*')
          $hasTS   = ((($qs['take'] -ne $null) -and ($qs['skip'] -ne $null)) -or ($Url -like '*/api/*'))

          # PowerShell 5.1 互換（?? を使わない）
          $pageSizeStr = FirstNonEmpty @($qs['itemsPerPage'], $qs['take'], $env:POS_PAGE_SIZE, '100')
          $pageSize = 0; [void][int]::TryParse($pageSizeStr, [ref]$pageSize); if ($pageSize -lt 1) { $pageSize = 100 }

          $startStr = FirstNonEmpty @($qs['currentPage'], '0')
          $start = 0; [void][int]::TryParse($startStr, [ref]$start); if ($start -lt 0) { $start = 0 }

          $maxPagesStr = FirstNonEmpty @($env:POS_MAX_PAGES, '50')
          $maxPages = 0; [void][int]::TryParse($maxPagesStr, [ref]$maxPages); if ($maxPages -lt 1) { $maxPages = 50 }

          $headers = @{
            'User-Agent'      = 'Mozilla/5.0'
            'Accept'          = '*/*'
            'Accept-Language' = 'ja,en-US;q=0.9,en;q=0.8'
            'Content-Type'    = 'application/json'
            'Referer'         = 'https://pos.mycalinks.com/'
            'Origin'          = 'https://pos.mycalinks.com'
          }
          if ($Cook) { $headers['Cookie'] = $Cook }
          if ($Auth) { $kv=$Auth.Split(':',2); if ($kv.Count -eq 2) { $headers[$kv[0].Trim()] = $kv[1].Trim() } }
          if ($Csrf) { $kv=$Csrf.Split(':',2); if ($kv.Count -eq 2) { $headers[$kv[0].Trim()] = $kv[1].Trim() } }

          $all = @()
          $prevHash = ''

          for ($i=$start; $i -lt $start + $maxPages; $i++) {
            if ($hasPage) {
              $u = Set-Q $Url 'currentPage' "$i"
              $u = Set-Q $u   'itemsPerPage' "$pageSize"
            } elseif ($hasTS) {
              $u = Set-Q $Url 'take' "$pageSize"
              $u = Set-Q $u   'skip' "$($i * $pageSize)"
            } else {
              $u = $Url
              if ($i -gt $start) { break }
            }

            $out = "data/raw_$i.bin"
            try {
              $resp = Invoke-WebRequest -Uri $u -Headers $headers -Method GET -MaximumRedirection 5 -OutFile $out -PassThru -ErrorAction Stop
              $code = [int]$resp.StatusCode
              $ct   = $resp.Headers['Content-Type']
            } catch {
              if ($_.Exception.Response) { $code=[int]$_.Exception.Response.StatusCode; $ct=$_.Exception.Response.ContentType } else { throw }
            }
            Write-Host "GET $u -> $code $ct"
            if ($code -ne 200) { break }

            $hash=(Get-FileHash -Algorithm MD5 $out).Hash
            if ($prevHash -and $prevHash -eq $hash) { break }
            $prevHash=$hash

            $json=$null
            if ("$ct" -match 'application/json') {
              try { $json = Get-Content $out -Raw | ConvertFrom-Json -ErrorAction Stop } catch {}
            } else {
              $html = Get-Content $out -Raw
              $m = [regex]::Match($html,'<script[^>]*id="__NEXT_DATA__"[^>]*>(.*?)</script>',[System.Text.RegularExpressions.RegexOptions]::Singleline)
              if ($m.Success) { try { $json = $m.Groups[1].Value | ConvertFrom-Json -ErrorAction Stop } catch {} }
            }

            $items=@()
            if ($json) {
              foreach($k in 'items','data','products','result','value') {
                if ($json.PSObject.Properties.Name -contains $k) {
                  $v=$json.$k
                  if ($v -is [System.Collections.IEnumerable]) { $items=@($v); break }
                }
              }
              if (-not $items -and ($json -is [System.Collections.IEnumerable])) { $items=@($json) }
            }

            if (-not $items -or $items.Count -eq 0) {
              if ($i -gt $start) { break } else { continue }
            }

            $all += $items
            if ($items.Count -lt $pageSize) { break }
          }

          $all | ConvertTo-Json -Depth 100 | Set-Content -Encoding UTF8 data/items.json
          Write-Host "Total items: $($all.Count)"

      - name: Convert JSON to CSV
        if: ${{ hashFiles('data/items.json') != '' }}
        run: |
          $py = @'
          import json, pandas as pd
          from pandas import json_normalize
          with open("data/items.json","r",encoding="utf-8") as f:
              data = json.load(f)
          if isinstance(data, dict):
              for k in ("items","data","products","result","value"):
                  if k in data and isinstance(data[k], list):
                      data = data[k]; break
          if not isinstance(data, list):
              data = [data]
          df = json_normalize(data, sep=".")
          df.to_csv("data/buylist.csv", index=False, encoding="utf-8")
          print("rows:", len(df), "cols:", len(df.columns))
          '@
          Set-Content -Encoding UTF8 -LiteralPath .\convert_json_to_csv.py -Value $py
          python .\convert_json_to_csv.py
          Get-ChildItem data

      - name: Build static pages
        env:
          OUT_DIR: docs
          PER_PAGE: "80"
          BUILD_THUMBS: "0"
        run: |
          $candidates = @("data\buylist.xlsx","data\buylist.csv","buylist.xlsx","buylist.csv")
          $input = $null
          foreach ($p in $candidates) { if (Test-Path $p) { $input = $p; break } }
          if (-not $input) { throw "No input data found (POS fetch failed and none in repo)." }
          Write-Host ("Using input: " + $input)
          python gen_buylist.py $input

      - name: Commit & push docs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if (git diff --cached --quiet) {
            Write-Host "No changes in docs/"
          } else {
            git commit -m "update buylist (auto)"
            git push
          }

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pos-debug
          path: data/**
